# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin

export PATH

# Java
export JAVA_HOME=/usr/lib/jvm/jre

# Hadoop
export HADOOP_HOME=/opt/hadoop-3.2.1
export HIVE_HOME=/opt/apache-hive-3.1.2-bin
export HBASE_HOME=/opt/hbase-2.2.4

#export HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop
#export HADOOP_INSTALL=$HADOOP_HOME
#export HADOOP_MAPRED_HOME=$HADOOP_HOME
#export HADOOP_COMMON_HOME=$HADOOP_HOME
#export HADOOP_HDFS_HOME=$HADOOP_HOME
#export HADOOP_YARN_HOME=$HADOOP_HOME
#export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
#export HADOOP_OPTS="-Djava.library.path=$HADOOP_COMMON_LIB_NATIVE_DIR"

#export JAVA_LIBRARY_PATH=$HADOOP_HOME/lib/native:$JAVA_LIBRARY_PATH
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HADOOP_HOME/lib/native

export PATH=$HBASE_HOME/bin:$HIVE_HOME/bin:$HADOOP_HOME/sbin:$HADOOP_HOME/bin:$PATH

